schema: olm.channel
name: stable
package: serverless-operator
entries:
  - name: "serverless-operator.v1.27.1"
  - name: "serverless-operator.v1.28.0"
    replaces: serverless-operator.v1.27.1
    skipRange: ">=1.27.0 <1.28.0"
